version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:80" # Port çakışmalarını önlemek için değiştirin
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0 # Belirli bir sürüm kullanın
    environment:
      MYSQL_DATABASE: restaurant-web-app
      MYSQL_ROOT_PASSWORD: "12345" # Basit bir şifre
    ports:
      - "3306:3306"
    volumes:
      - ./restaurant-web-app.sql:/docker-entrypoint-initdb.d/restaurant-web-app.sql # SQL dosyasını ekledik

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80" # Port çakışmalarını önlemek için değiştirin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: "12345" # Aynı şifreyi buraya da ekleyin
    depends_on:
      - db
